"""Error codes for mcs-masterdata."""

# Error codes
MASTERDATA_INVALID = "MASTERDATA_INVALID"
CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND"
COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
VALIDATION_ERROR = "VALIDATION_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"

