"""Error codes for mcs-orchestrator."""

# Error codes
MASTERDATA_INVALID = "MASTERDATA_INVALID"
CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND"
NOT_CONTRACT_MAIL = "NOT_CONTRACT_MAIL"
PDF_NOT_FOUND = "PDF_NOT_FOUND"
CUSTOMER_MATCH_LOW_SCORE = "CUSTOMER_MATCH_LOW_SCORE"
CUSTOMER_CONTACT_MISMATCH = "CUSTOMER_CONTACT_MISMATCH"
FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
DIFY_CONTRACT_FAILED = "DIFY_CONTRACT_FAILED"
DIFY_ORDER_PAYLOAD_BLOCKED = "DIFY_ORDER_PAYLOAD_BLOCKED"
ERP_CREATE_FAILED = "ERP_CREATE_FAILED"
MULTI_PDF_ATTACHMENTS = "MULTI_PDF_ATTACHMENTS"
MULTI_CUSTOMER_AMBIGUOUS = "MULTI_CUSTOMER_AMBIGUOUS"
FILE_ACCESS_BLOCKED = "FILE_ACCESS_BLOCKED"
RUN_NOT_IN_MANUAL_REVIEW = "RUN_NOT_IN_MANUAL_REVIEW"
INVALID_DECISION = "INVALID_DECISION"
STALE_DECISION = "STALE_DECISION"
PERMISSION_DENIED = "PERMISSION_DENIED"


class OrchestratorError(Exception):
    """Orchestrator error exception."""

    def __init__(self, code: str, reason: str, details: dict | None = None):
        """Initialize orchestrator error."""
        self.code = code
        self.reason = reason
        self.details = details or {}
        super().__init__(f"{code}: {reason}")

