/**
 * Common constants for MCS Gateway
 */

export const HEADER_REQUEST_ID = 'X-Request-ID';
export const HEADER_TENANT_ID = 'X-MCS-Tenant-ID';
export const HEADER_USER_ID = 'X-MCS-User-ID';
export const HEADER_SCOPES = 'X-MCS-Scopes';
export const HEADER_GRAPH_NAME = 'X-MCS-Graph-Name';
export const HEADER_GRAPH_VERSION = 'X-MCS-Graph-Version';
export const HEADER_CLIENT_APP = 'X-MCS-Client-App';
export const HEADER_TRACEPARENT = 'traceparent';

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  VERSION_NOT_ALLOWED: 'VERSION_NOT_ALLOWED',
  INSUFFICIENT_SCOPE: 'INSUFFICIENT_SCOPE',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const HTTP_STATUS_MAP = {
  401: ERROR_CODES.UNAUTHORIZED,
  403: ERROR_CODES.PERMISSION_DENIED,
  404: ERROR_CODES.NOT_FOUND,
  429: ERROR_CODES.RATE_LIMITED,
  502: ERROR_CODES.UPSTREAM_UNAVAILABLE,
  503: ERROR_CODES.UPSTREAM_UNAVAILABLE,
  504: ERROR_CODES.UPSTREAM_UNAVAILABLE,
} as const;

