"""Error codes for mcs-gateway."""

# ERP errors
ERP_CONNECTION_FAILED = "ERP_CONNECTION_FAILED"
ERP_ORDER_CREATE_FAILED = "ERP_ORDER_CREATE_FAILED"
ERP_AUTH_FAILED = "ERP_AUTH_FAILED"
ERP_INVALID_RESPONSE = "ERP_INVALID_RESPONSE"

# Generic errors
EXTERNAL_SYSTEM_ERROR = "EXTERNAL_SYSTEM_ERROR"
INVALID_REQUEST = "INVALID_REQUEST"

