"""Error codes for mcs-listener."""

# Generic errors
MESSAGE_FETCH_FAILED = "MESSAGE_FETCH_FAILED"
MESSAGE_PARSE_FAILED = "MESSAGE_PARSE_FAILED"
ORCHESTRATOR_CALL_FAILED = "ORCHESTRATOR_CALL_FAILED"
LISTENER_CONNECTION_FAILED = "LISTENER_CONNECTION_FAILED"

# Email-specific errors
EMAIL_FETCH_FAILED = "EMAIL_FETCH_FAILED"
EMAIL_PARSE_FAILED = "EMAIL_PARSE_FAILED"

# WeChat-specific errors
WECHAT_API_ERROR = "WECHAT_API_ERROR"
WECHAT_AUTH_FAILED = "WECHAT_AUTH_FAILED"

